### ISSUE TITLE
How to get channel key?

### ISSUE THREAD

**Issue by leenux** [emitter-io/csharp#21]
My work step:
1 download version 2.7 for linux amd64
2 run `./emiter`
3 edit emiter.conf and fill license
4 re-run `./emiter`
5 console is:
```
$ ./emitter 
2020/11/16 14:15:11 [service] configured logging provider (stderr)
2020/11/16 14:15:11 [service] configured message storage (inmemory)
2020/11/16 14:15:11 [service] configured usage metering (noop)
2020/11/16 14:15:11 [service] configured contracts provider (single)
2020/11/16 14:15:11 [service] configured monitoring sink (self)
2020/11/16 14:15:11 [service] configured node name (00:0c:29:dc:50:43)
2020/11/16 14:15:11 [service] starting the listener (0.0.0.0:8080)
2020/11/16 14:15:11 [tls] unable to configure certificates, make sure a valid cache or certificate is configured
2020/11/16 14:15:11 [service] service started
```
6 broswer open url `http://127.0.0.1:8080/genkey`
7 fill `Secret Key` and `Target Channel` and click `Genrate Key` button
8 didnot get channel key and got toast`the security key provided is not authorized to perform this operation`

Try the same use docker by https://github.com/emitter-io/emitter#get-license

Quest: How to get the channel key?

**Comment by leenux** [comment]
miss respones

**Comment by bagitom** [comment]
hello!
Late response, but...
I've created it on my server just couple of minutes before. The steps was the following:
1) run emitter.io docker container
2) check docker log for an entry like this: 
2022/01/12 20:11:24 [license] generated new secret key: XXXXXXXXXXXXXXXX

3) at http://emitter.yourserver.com/keygen  copy the license key, into the first text box (labelled by: secret key) found in the log above.

4) click on "generate key" button, and you will get the key, wich you shuld use it in your script

+1 let me know how is using this key given at step 4)  in a client side  script not unsecure?? It is shown in the DOM, and can be stolen. Isn't it?
