### ISSUE TITLE
Emitter Broker- C# version - Mismatch in the messages sequence

### ISSUE THREAD

**Issue by sandeeprachamalla89** [emitter-io/csharp#4]
I am consuming the emitter broker C# version. when we send the messages in PUB/SUB channels through Broker, they are delivered in the form of bytes. We observed that , the messages are not getting delivered in a sequence in which they received. Can you help us where we need to point in the code to debug this issue?
Thanks,
Sandeep

**Comment by Florimond** [comment]
"the messages are not getting delivered in a sequence in which they received"

I'm not sure I see exactly what you mean by that, but I'm gonna assume you are rolling your own broker and seeing that the client does not receive message in the same order as the broker does.

That seems quite normal to me. You should not expect any sequence to be respected, as you are supposed to have a cloud of brokers with messages being exchanged all over the place. Consistency is eventual. CRDTs working to reconcile states between brokers.

You can check the code of this [collaborative todo list](https://github.com/Florimond/emitter-demo-todo) and observe how no order of delivery is ever expected.
