### ISSUE TITLE
Nuget and github versions?

### ISSUE THREAD

**Issue by postacik** [emitter-io/csharp#9]
Hi,

Nuget version of this library is 1.0.41. (https://www.nuget.org/packages/Emitter/)

Github latest release version is 4.3.0.0.

Which one is more recent?

**Comment by Florimond** [comment]
Hi,

the version on Github is more recent. The nugget wasn't updated because the build currently has a small issue that I have to fix.

**Comment by postacik** [comment]
Thanks for the information
